### ISSUE TITLE
تدقيق المعاملات والتسميات

### ISSUE THREAD

**Issue by linuxscout** [tarekDZ2019/moadaly-App#1]
يرجى مراجعة معاملات السنة الأولى
[http://dpinfo.univ-bouira.dz/wp-content/uploads/2019/05/Mi2019-canevas.pdf](http://dpinfo.univ-bouira.dz/wp-content/uploads/2019/05/Mi2019-canevas.pdf)
وكذلك تسمية السنة الثانية وموادها للسنة الدراسية الجديدة
يمكن الاطلاع على
[http://dpinfo.univ-bouira.dz/wp-content/uploads/2019/07/2info-new.pdf](http://dpinfo.univ-bouira.dz/wp-content/uploads/2019/07/2info-new.pdf)

**Comment by tarek-berkane** [comment]
تم تحديث و تصحيح جميع معاملات السنة الاولى و تحديث التسميات  للسنة الثانية و فق لسنة الدراسية الجديدة 
يمكنك تحمبل تطبيق معدلي الجديد من الرابط  
https://drive.google.com/open?id=1ECDoTvPSR24LW7aVreTvEhCETzYDvFl2
شكرا
